# Generated by Django 2.2.7 on 2019-11-28 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('represent_image', models.ImageField(default='', upload_to='images/')),
                ('create_date', models.DateField(default=datetime.datetime(2019, 11, 28, 8, 54, 28, 468240))),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('phone_number', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('create_date', models.DateField(default=datetime.datetime(2019, 11, 28, 8, 54, 28, 468778))),
            ],
        ),
    ]
