# Generated by Django 2.2.7 on 2019-12-07 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_auto_20191207_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deal_week',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 7, 4, 46, 23, 437845)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 7, 4, 46, 23, 438495)),
        ),
    ]
