# Generated by Django 2.2.7 on 2019-12-07 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_auto_20191207_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 7, 4, 46, 32, 773042)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 7, 4, 46, 32, 773755)),
        ),
    ]
